### ISSUE TITLE
SPI.begin() locks up MKR ZERO

### ISSUE THREAD

**Issue by BrenuDev** [ImpulseAdventure/Waveshare_ILI9486#6]
I am testing the lib and the SPI.begin() should be moved before setting the parameters.
Otherwise the SPI object is not initialized and crashes the board.

**Comment by ImpulseAdventure** [comment]
Thank you @velbn -- I have now made the change to the initialization.

Note that I am in the process of replacing the driver altogether with a new version from MHotchin that will use SPI transactions instead.

thx
