### ISSUE TITLE
Current version not compatible with GUISlicer

### ISSUE THREAD

**Issue by sjbaird** [ImpulseAdventure/Waveshare_ILI9486#7]
It seems that this version is missing the GFX files

**Comment by ImpulseAdventure** [comment]
Hi! You are correct that the updated version has changed set of include files.

A new version of GUIslice has been released that uses the updated Waveshare_ILI9486 files.
This version is not yet released via the Arduino IDE library manager, so for now you will need to [manually update the library from GitHub](https://github.com/ImpulseAdventure/GUIslice/wiki/Installing-GUIslice-on-Arduino#installing-from-github-source).

Let me know if you have any difficulties.
Thanks!

**Comment by ImpulseAdventure** [comment]
Closing as GUIslice 0.15 has been released to the Arduino IDE library manager
